using UnityEngine;


[RequireComponent(typeof(CharacterController))]
public class PlayerStealthController : MonoBehaviour
{
    [Header("Stealth Parameters")]
    [Tooltip("Base noise generated even when standing still (e.g., breathing/gear rustling).")]
    [SerializeField] private float baseNoiseLevel = 0.5f;

    [Tooltip("Multiplier for noise generated by locomotion speed.")]
    [SerializeField] private float movementNoiseMultiplier = 2.0f;

    public float CurrentNoiseRadius { get; private set; }

    private CharacterController characterController;

    private void Awake()
    {
        characterController = GetComponent<CharacterController>();
    }

    private void Update()
    {
        CalculateNoiseEmission();
    }


    private void CalculateNoiseEmission()
    {
        Vector3 horizontalVelocity = new Vector3(characterController.velocity.x, 0, characterController.velocity.z);
        float currentSpeed = horizontalVelocity.magnitude;

        CurrentNoiseRadius = baseNoiseLevel + (currentSpeed * movementNoiseMultiplier);
    }

    private void OnDrawGizmos()
    {
        Gizmos.color = new Color(1f, 0f, 0f, 0.2f);
        Gizmos.DrawSphere(transform.position, CurrentNoiseRadius);
    }
}